import Head from "next/head";
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import styled from "styled-components";
// import { ConnectWallet, useAddress } from "@thirdweb-dev/react";
import Dashboard from "../components/Dashboard";

export default function Home() {
  // const address = useAddress();

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Wrapper>
          <Dashboard />
          {/* {address ? (
          ) : (
            <div>
              <TitleWrapper>Please connect your wallet</TitleWrapper>
              <ConnectWallet
                className="connect-wallet"
                colorMode="dark"
                accentColor="#0052ff"
              />
            </div>
          )} */}
        </Wrapper>
      </main>

      <footer className=""></footer>
    </div>
  );
}

const Wrapper = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
  max-width: 100vw;
`;

const TitleWrapper = styled.p`
  font-size: 20px;
  font-weight: 600;
`;
